---
title: "Marine Population Dynamics"
subtitle: Homework 2 
author: Alexa L. Fredston
date: April 2025
format: pdf
editor: visual
execute:
  echo: false
  warning: false
---

# Part 1

Find a time-series. It can be the same one as last week, or if you want to start over with a different time-series, please reference the details in Homework 1 (and please also answer Homework 1 Question 1 describing the new data so I understand it). 

**Question 1:** Include a plot of the time-series (N vs. t); it can be the same as the plot from last week. Last week I asked you to choose one of the models we discussed that might fit these data. Do you still think that is the best choice for your data? Is there another model that might qualitatively reproduce the patterns in your data better? Why or why not?

**Question 2:** *Qualitatively*, does it look like the population reached equilibrium at any point? Describe at what relative N the equilibrium was reached, and relatively for how long; or describe why it looks to you like there was no equilibrium. (I understand real data are noisy, so you can be approximate here.) 

**Question 3:** Try to sketch by hand a curve of $dN/dt$ vs. $N$ for your population (based on the real data, or maybe imagine a smoothed line through the real data). Recall that taking the derivative of a function represents calculating the slope at every point, so go along the graph in sections, draw the best straight line through it, and then estimate the slope of that line. Include a picture here (or turn this in as a hard copy in class, whichever you prefer.) 

**Question 4:** Explain how you could've gotten the answer to Question 1 (about equilibria) just from the hand-drawn figure in Question 2, even if you didn't have the time-series plot (N vs t). If you think the population may have reached an equilibrium at any point (again, these are guesstimates; you don't need to be exact) state whether it is unstable or stable, and why. 

# Part 2

Let's imagine the population you chose is now being harvested by humans---for food or industrial use, for example. We'll start with a constant-harvest scenario. 

**Question 5:** Re-draw the plot from Question 2 (or add to it) with different values of a constant harvest, the way we did in class. Try to plot a low value, a high value ($H_{max}$) . 

**Question 6:** In a few sentences and/or a plot, explain what effect you think constant harvest would have on the N vs. t plot from Question 1 *if harvest kicked in once you were at a moderate population size*. What happens to the shape of the curve at small N? At large N? 

**Question 7:** Do you think your population is more likely to avoid collapse under a constant harvest or constant effort scenario? Explain your answer in 1-2 sentences. 
